"""empty message

Revision ID: 9d63822d82e3
Revises: 
Create Date: 2021-04-04 21:54:06.011762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d63822d82e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kural',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Number', sa.String(), nullable=True),
    sa.Column('Line1', sa.String(), nullable=True),
    sa.Column('Line2', sa.String(), nullable=True),
    sa.Column('Translation', sa.String(), nullable=True),
    sa.Column('couplet', sa.String(), nullable=True),
    sa.Column('mv', sa.String(), nullable=True),
    sa.Column('sp', sa.String(), nullable=True),
    sa.Column('mk', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('transliteration1', sa.String(), nullable=True),
    sa.Column('transliteration2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kural')
    # ### end Alembic commands ###
